// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4group_lasso_hierarchical_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4horseshoe_group_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4horseshoe_group_plus_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4horseshoe_plus_wo_group_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4group_lasso_hierarchical_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4group_lasso_hierarchical_mod, 0},
    {"_rcpp_module_boot_stan_fit4horseshoe_group_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4horseshoe_group_mod, 0},
    {"_rcpp_module_boot_stan_fit4horseshoe_group_plus_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4horseshoe_group_plus_mod, 0},
    {"_rcpp_module_boot_stan_fit4horseshoe_plus_wo_group_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4horseshoe_plus_wo_group_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ShrinkingMidas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
